version: "3.7"

services:
  # PHP service
  pa-php:
    container_name: PA-PHP
    build:
      context: ./php
      args:
        TIMEZONE: ${TIMEZONE}
    volumes:
      - ../app/www:/var/www
    ports:
      - ${PHP_9000}:9000
      - ${APACHE_80}:80
      - ${APACHE_443}:443
    expose:
      - 9000
    restart: always
    networks:
      - php_apache_app
      - db_network

networks:
  php_apache_app:
    name: ${PROJECT_NETWORK}
  db_network:
    external: true
    name: ${DB_NETWORK}
